import { jsPDF } from 'jspdf';
import { getMonthString, getMonthlyTotal, getCategoryBreakdown } from './calculations';

export function exportMonthlyReport(state) {
  const doc = new jsPDF();
  const monthStr = getMonthString();
  const monthLabel = new Date().toLocaleDateString('en-IN', { month: 'long', year: 'numeric' });

  const monthlyTotal = getMonthlyTotal(state.logs, monthStr);
  const breakdown = getCategoryBreakdown(state.logs, 'month');
  const completedCount = Object.values(state.completedActions).filter(Boolean).length;
  const totalImpact = Object.entries(state.completedActions)
    .filter(([, done]) => done)
    .reduce((sum, [id]) => {
      const action = state.actionsLibrary?.find?.((a) => a.id === id);
      return sum + (action?.impact || 0);
    }, 0);

  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  doc.setFillColor(45, 106, 79);
  doc.rect(0, 0, pageWidth, 40, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('EcoTrack Monthly Report', pageWidth / 2, 18, { align: 'center' });

  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(monthLabel, pageWidth / 2, 30, { align: 'center' });

  y = 55;
  doc.setTextColor(45, 106, 79);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Carbon Footprint Summary', 20, y);

  y += 12;
  doc.setTextColor(60, 60, 60);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');

  doc.text(`Total Emissions: ${monthlyTotal.toFixed(1)} kg CO₂e`, 20, y);
  y += 8;
  doc.text(`Daily Average: ${(monthlyTotal / 30).toFixed(1)} kg CO₂e/day`, 20, y);
  y += 8;

  if (state.quizResults) {
    doc.text(`Quiz Baseline: ${state.quizResults.dailyTotal} kg CO₂e/day`, 20, y);
    y += 8;
    const change = ((monthlyTotal / 30) - state.quizResults.dailyTotal);
    const changeLabel = change <= 0 ? 'reduction' : 'increase';
    doc.text(`Change from baseline: ${Math.abs(change).toFixed(1)} kg/day ${changeLabel}`, 20, y);
    y += 8;
  }

  if (state.goals?.monthlyTarget) {
    doc.text(`Monthly Target: ${state.goals.monthlyTarget} kg CO₂e`, 20, y);
    y += 8;
    const progress = ((state.goals.monthlyTarget - monthlyTotal) / state.goals.monthlyTarget * 100).toFixed(0);
    doc.text(`Target Progress: ${progress > 0 ? progress + '% under target' : Math.abs(progress) + '% over target'}`, 20, y);
    y += 8;
  }

  y += 8;
  doc.setTextColor(45, 106, 79);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Category Breakdown', 20, y);

  y += 10;
  doc.setTextColor(60, 60, 60);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');

  if (breakdown.length === 0) {
    doc.text('No logs recorded this month.', 20, y);
    y += 8;
  } else {
    breakdown.forEach((cat) => {
      const pct = monthlyTotal > 0 ? ((cat.value / monthlyTotal) * 100).toFixed(0) : 0;
      doc.text(`${cat.name}: ${cat.value} kg CO₂e (${pct}%)`, 25, y);
      y += 7;
    });
  }

  y += 8;
  doc.setTextColor(45, 106, 79);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Actions & Progress', 20, y);

  y += 10;
  doc.setTextColor(60, 60, 60);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(`Completed Actions: ${completedCount}`, 20, y);
  y += 7;
  doc.text(`Estimated Impact Saved: ${totalImpact} kg CO₂e/month`, 20, y);
  y += 7;
  doc.text(`Current Streak: ${state.streak?.current || 0} days`, 20, y);
  y += 7;
  doc.text(`Longest Streak: ${state.streak?.longest || 0} days`, 20, y);
  y += 7;
  doc.text(`Badges Earned: ${state.earnedBadgeIds?.length || 0}`, 20, y);

  y += 12;
  doc.setTextColor(45, 106, 79);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Activity Log', 20, y);

  y += 10;
  doc.setTextColor(60, 60, 60);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');

  const monthLogs = state.logs.filter((l) => l.date.startsWith(monthStr)).slice(-15);
  if (monthLogs.length === 0) {
    doc.text('No activities logged this month.', 20, y);
  } else {
    monthLogs.forEach((log) => {
      if (y > 270) {
        doc.addPage();
        y = 20;
      }
      doc.text(
        `${log.date} | ${log.category} | ${log.itemLabel} | ${log.quantity} ${log.unit} | ${log.emissions} kg`,
        20,
        y
      );
      y += 6;
    });
  }

  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(
    'Generated by EcoTrack — Carbon Footprint Awareness Platform | Data stored locally',
    pageWidth / 2,
    285,
    { align: 'center' }
  );

  doc.save(`EcoTrack-Report-${monthStr}.pdf`);
}